image: node

stages:
  - install
  - build
  - quality

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .yarn

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

install:
  stage: install
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn build

build:
  stage: build
  script:
    - yarn build
  dependencies:
    - install

linting:
  stage: quality
  script:
    - yarn lint
  dependencies:
    - install

test:unit:
  stage: quality
  script:
    - yarn test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

test:e2e:
  stage: quality
  image: cypress/base
  dependencies:
    - install
    - build
  coverage: /Statements\s+:\s(\d+.?\d+)%/
  script:
    - yarn serve -s build -l 3000 & yarn wait-on http://localhost:3000
    - yarn cypress run --record --key 8526982a-d856-47f8-a6a8-e005048b9fc3 --group gitlab-ci