image: node

stages:
  - install
  - build
  - quality
  - deploy
  - audit

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

install:
  stage: install
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn build
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 60 mins
    paths:
      - .yarn/
      - node_modules/

build:
  stage: build
  script:
    - CI=false yarn build
  artifacts:
    paths:
      - build
    expire_in: 60 mins
  dependencies:
    - install

linting:
  stage: quality
  script:
    - yarn lint
  dependencies:
    - install

test:unit:
  stage: quality
  script:
    - yarn test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

test:e2e:
  stage: quality
  image: cypress/base
  dependencies:
    - install
    - build
  script:
    - yarn serve -s build -l 3000 & yarn wait-on http://localhost:3000
    - yarn cypress run --record --key 8526982a-d856-47f8-a6a8-e005048b9fc3 --group gitlab-ci
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 day